version: '3'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - peerjs
  peerjs:
    image: peerjs/peerjs-server
    command: peerjs --port 9000 --path /peerjs
    ports:
      - "9000:9000"
    restart: always
