version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
  peerjs:
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
    restart: always
